### ISSUE TITLE
Cannot even open launcher

### ISSUE THREAD

**Issue by syntus** [torbsd/torbsd.github.io#14]
When I try to run tor-browser.desktop I am told it cannot execute the child process, what am I doing wrong?

**Comment by gman999** [comment]
Greetings.

I assume you're running a recent snapshot with 6.5.2 TB.

Look at the properties of the Tor Browser icon, then select the launcher tab.  Does the command show /usr/local/bin/tor-browser?

**Comment by gman999** [comment]
We haven't heard anything else from you, and TB 7.0.2 is out for OpenBSD in the -current ports, so we'll close this issue.
