### ISSUE TITLE
Tunneling OS data through tor on BSD platforms. Tails/BSD?

### ISSUE THREAD

**Issue by vanhecke** [torbsd/torbsd.github.io#3]
It would be helpful for the tor network to not only add diversity to its nodes but also its clients.
I applaud TDP's efforts on the Torbrowser port for OpenBSD, but more could be done.

I realize that making a BSD-based version of Tails that incorporates all of Tails' features right now is out of scope. But by just configuring an OpenBSD installation to function more like Tails, one would achieve a reasonably secure alternative to Tails.

A SiteXX.tgz for OpenBSD that includes the some of the same things as tails would be ideal:
- Automatically install packages such as tor, torbrowser, XFCE/GNOME3, PGP/GPG, KeePass, a mailclient
- automatically start tor on startup
- **pf.conf to route everything through tor**
- Desktop XFCE/GNOME3 metapackage
- automatic OpenBSD upgrading

It might also be easier to patch the install script and add a diskencryption setup in there.

So, a torbsd-desktop, good idea / bad idea?

**Comment by gman999** [comment]
Greetings Vanhecke.

Outside of TB on OpenBSD (and ultimately to the other BSDs), we are primarily focused on the Tor network level.

To be honest, we're _not_ in a position to do much more than we are doing at this point. TDP is unfunded, and we do a lot of related dev work off-GitHub as it is.

We actually have discussed doing a TAILS version on OpenBSD in the past.  It's not enormously difficult, and there certainly is a need, but we aren't in a position spend the time on it at this point.

If we were funded to do such a project, we would certainly jump on it.  At this point, it unfortunately has to remain something we'd love to do in the future.

Thanks for your interest and support of TDP.

gman999

**Comment by gman999** [comment]
Feel free to reopen issue if you still want to reply.
