### ISSUE TITLE
Pre-configured OpenBSD -stable resflash images for Tor non-exit relays

### ISSUE THREAD

**Issue by bconway** [torbsd/torbsd.github.io#8]
I enjoyed George's talk about the Tor BSD Diversity Project at BSDCan this year and spent some time writing a couple scripts to build pre-configured OpenBSD resflash images for Tor non-exit relays. I'm running them now on a couple VPS/VM providers quite successfully. The README includes anything one might need to know to get them running securely:

https://stable.rcesoftware.com/pub/resflash/tor/

Additional information:

https://stable.rcesoftware.com/resflash/

Like my non-Tor pre-canned images, I expect to keep them up to date with the latest OpenBSD -stable branch.

**Comment by gman999** [comment]
Great stuff Brian. Very excited to test.

I downloaded the other day, but there was the MD5 checksum didn't match.  I'll take a look again tomorrow.

**Comment by bconway** [comment]
Thanks. Please note that the .cksum file applies to the uncompressed image/filesystem and is used in the upgrade process or for verifying dd correctness. The arch-level SHA512 file has checksum for all files as they are downloaded.

Also, I expect to push new images tomorrow with some tuning of tmpfs sizes and login.conf settings based on my trial runs with the images.
